// <auto-generated />
using System;
using CVForm.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CVForm.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210623135507_InitialSchema")]
    partial class InitialSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CVForm.DataBase.Nationality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NationalityName")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.ToTable("Nationalities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NationalityName = "Lebanese"
                        },
                        new
                        {
                            Id = 2,
                            NationalityName = "Russian"
                        },
                        new
                        {
                            Id = 3,
                            NationalityName = "French"
                        },
                        new
                        {
                            Id = 4,
                            NationalityName = "American"
                        });
                });

            modelBuilder.Entity("CVForm.DataBase.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SkillName = "Java"
                        },
                        new
                        {
                            Id = 2,
                            SkillName = "HTML"
                        },
                        new
                        {
                            Id = 3,
                            SkillName = "PHP"
                        },
                        new
                        {
                            Id = 4,
                            SkillName = "C"
                        },
                        new
                        {
                            Id = 5,
                            SkillName = "C++"
                        },
                        new
                        {
                            Id = 6,
                            SkillName = "C#"
                        },
                        new
                        {
                            Id = 7,
                            SkillName = "Dot Net Core"
                        },
                        new
                        {
                            Id = 8,
                            SkillName = "Python"
                        });
                });

            modelBuilder.Entity("CVForm.DataBase.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("Date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(90)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("Binary");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<bool?>("Sex")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NationalityUser", b =>
                {
                    b.Property<int>("NationalitiesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("NationalitiesId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("NationalityUser");
                });

            modelBuilder.Entity("SkillUser", b =>
                {
                    b.Property<int>("SkillsId")
                        .HasColumnType("int");

                    b.Property<int>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("SkillsId", "UsersUserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("SkillUser");
                });

            modelBuilder.Entity("NationalityUser", b =>
                {
                    b.HasOne("CVForm.DataBase.Nationality", null)
                        .WithMany()
                        .HasForeignKey("NationalitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVForm.DataBase.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SkillUser", b =>
                {
                    b.HasOne("CVForm.DataBase.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CVForm.DataBase.User", null)
                        .WithMany()
                        .HasForeignKey("UsersUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
